---
abstract: 'Pegex Crontab Parser'
author:
  - 'Ingy döt Net <ingy@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.59
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: Pegex::Crontab
name: Pegex-Crontab
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Pegex: 0.21
  lexicals: 0.21
  perl: 5.10.0
resources:
  homepage: https://github.com/ingydotnet/pegex-crontab-pm/tree
  license: http://dev.perl.org/licenses/
  repository:
    type: git
    url: git://github.com/ingydotnet/pegex-crontab-pm.git
    web: https://github.com/ingydotnet/pegex-crontab-pm/tree
version: 0.12
